### ISSUE TITLE
Milestones for Friday 2/9

### ISSUE THREAD

**Issue by cbartolm** [epicfaace/laughing-memory#4]
· Explore 2 other new kernels (feel free to choose the one that most interests you) + Review the one that was due for today. Submission format: github + colaboratory. - @epicfaace  & @cbartolm

· Paper to read (https://people.eecs.berkeley.edu/~jonlong/long_shelhamer_fcn.pdf) + brief report of it - @yzhan132 

Safe flight Yiguang! We will keep you posted with the latest news ;)

**Comment by epicfaace** [comment]
Merged #7.
